context:
  version: 3.0.0

package:
  name: doxdox
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/doxdox/-/doxdox-${{ version }}.tgz
  sha256: fcab12e1cacd07ea57ef32cbb66accd54a7421c6b7e47ac480b6a0bf6a78bf3e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - doxdox --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: JSDoc to Markdown, Bootstrap, and custom JavaScript template documentation generator.
  homepage: https://github.com/docsbydoxdox/doxdox
  repository: https://github.com/docsbydoxdox/doxdox

extra:
  recipe-maintainers:
    - danielnachun
